### ISSUE TITLE
What's the meaning of data in preemption traces?

### ISSUE THREAD

**Issue by jokerwyt** [skypilot-org/spot-traces#1]
Hi, I am curious about the meaning of data in preemption traces like `preemption/1-node/aws-04-22-2023/us-west-2c_v100_1.json`. The data contains 0, 1, and even floats like `0.918`, which makes it confusing. I also scanned the paper but did not find any description of how the preemption traces are collected (maybe I missed sth?) 

Thanks for attention!

**Comment by Michaelvll** [comment]
Thanks for the question @jokerwyt! Please refer to the README file in the repo for the structure and meaning of the data: https://github.com/skypilot-org/spot-traces/tree/main?tab=readme-ov-file#data-description

0 and 1 indicate the number of the available spot instances at the timestamp.

For the `0.918` floats, if you check the json file, they are under a different field called `prices`, i.e., for some of the traces we also collected the real-time pricing of the spot instances for reference.

I am closing this issue for now, but please feel free to re-open it if the questions are not resolved. : )
